### ISSUE TITLE
[BUG] Molten Tungsten Mod allows to crast Turbo Transport Belt before researching Turbo Transport Belt

### ISSUE THREAD

**Issue by Nipahu** [LuziferSenpai/factorio-mods#10]
**Describe the bug**
Currently the casting recipes for the Turbo Transport Belt and related items are unlocked after researching "Tungsten Steel" instead after researching "Turbo Transport Belt". 

Edit: I just realized "Tungsten Steel" unlocked various casting recipes you shouldn't have access after just having researched "Tungsten Steel", like the Fusion Reactor and Generator.

**Expected behavior**
Casting recipes for Turbo Transport Belt and related items should only be unlocked after researching "Turbo Transport Belt".

**Mod Information**
- Mod Name: Molten Tungsten
- Mod Version: 0.0.7

**Comment by LuziferSenpai** [comment]
That is something I cant really change, without a lookup table for recipes that would need to be unlocked later.
