### ISSUE TITLE
[FEATURE] Open the Captain's Log GUI focused to the ship I am looking at, if any

### ISSUE THREAD

**Issue by klardotsh** [LuziferSenpai/factorio-mods#14]
**Is your feature request related to a problem? Please describe.**

If I'm looking at a ship "Foo", it's confusing when Captain's Log opens to some other ship "Bar" when I click the header button.

**Describe the solution you'd like**

See title

**Describe alternatives you've considered**

Unknown?

**Additional context**

Thanks for making this mod! I appreciate you!

**Comment by LuziferSenpai** [comment]
Added with https://github.com/LuziferSenpai/factorio-mods/commit/af633c71f0bdb58b1f367545502d96805754c1f5 as a option. Its released as version 0.0.6.

**Comment by klardotsh** [comment]
Thank you!
