### ISSUE TITLE
[BUG] More Casting Startup Error

### ISSUE THREAD

**Issue by Alistair-Afton** [LuziferSenpai/factorio-mods#16]
I get the following error message on game start:

Failed to load mods: The given sprite rectangle (left_top=0x0, right_bottom=256x256) is outside the actual sprite size (left_top=0x0, right_bottom=64x64).
See the log file for more information.: __more-casting__/graphics/64x64-empty.png

**Comment by LuziferSenpai** [comment]
https://github.com/LuziferSenpai/factorio-mods/issues/13

**Comment by LuziferSenpai** [comment]
I uploaded a temporary fix for now, we will see the response from the devs.
