### ISSUE TITLE
[BUG] More Casting & Molten Tungsten recipes are all unlocked at the Foundry, allowing you to skip researching certain recipes

### ISSUE THREAD

**Issue by Samario1** [LuziferSenpai/factorio-mods#17]
![image](https://github.com/user-attachments/assets/56c5761d-0b0d-41d4-a280-447f07485468)
E.G. I haven't researched artillery yet, but the casting recipe allows me to make the artillery turret anyway
It should probably move the unlock of the recipe to the same tech as its source recipe instead of shoving them all onto Foundries

**Comment by LuziferSenpai** [comment]
That is something I cant really change, without a lookup table for recipes that would need to be unlocked later.
