### ISSUE TITLE
[FEATURE]More Casting Suggestion, more recipes

### ISSUE THREAD

**Issue by disposablemlarky** [LuziferSenpai/factorio-mods#19]
Add in the values for some of the intermediates to your table so you can whole cast items.
The argument for balance is that if you one shot cast something, you lose out on iterative production bonuses, trading complexity instead.
I've tried it myself and found that its a fun twist and naturally self balances.

**Comment by LuziferSenpai** [comment]
I dont have any intentions to add more variables, I wanted to only use the things the foundary can do on its own.
