### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by lstndfnd001** [LuziferSenpai/factorio-mods#20]
im not sure this is capable but i am wanting to use your Automatic Coupling mod to run fully dynamic trains. the issue i have is i cannot read the wagons alone at a stop. i want to be able to dispatch a train from one location to pick up empty wagons from a rail yard and deliver to a specific stop, then when filled pick them back up and take them back to the yard for other trains to pickup and identify when the wagons are loaded to be taken to other locations and emptied then brought back.

the problem is there is no way to identify if a wagon is loaded or unloaded unless a locomotive is attached and in Automatic mode. i would like some sort of signal to read if wagons only at a stop have cargo or not. if this is impossible then i understand.

**Comment by LuziferSenpai** [comment]
This I cant and will not implement.
There was a example for this inside my old mod simple circuit trains, you can still look at it with factorio version 1.1.
