### ISSUE TITLE
[BUG] There are recipees that get unlocked that shouldn't be there + There seem to be duplicate recipees

### ISSUE THREAD

**Issue by JimTheGentlemanGR** [LuziferSenpai/factorio-mods#21]
The moment you research foundries you get blasted with a ton of recipees for items to make in foundries, however a lot of those recipees are for items you haven't even unlocked yet. For example: Being able to cast Railgun Bullets when you haven't even researched them. You also get duplicate recipees such as having two recipees for belts (seen in screen shot below)

**Screenshots**
![bugreportphoto1](https://github.com/user-attachments/assets/87901740-1201-4b59-bffe-8a43050a28c1)
You can see some of the recipees that are being duplicated /\

![bugreportphoto2](https://github.com/user-attachments/assets/cd65f942-6a4c-4e08-bcc2-666206083a87)
Just to show I haven't researched express belts /\

**Mod Information**
- Mod Name: More Casting
- Mod Version: 0.0.10

**Additional context**
I have the game modded with a couple of mods, but this shouldn't cause the dupling of vanilla items, or allow to cast items that are modded or vanilla but not researched

**Comment by LuziferSenpai** [comment]
Not a bug, go check the mod settings.
And where is there a duplicate recipe?

**Comment by JimTheGentlemanGR** [comment]
![randomahname2](https://github.com/user-attachments/assets/262e7125-eea9-42b6-acca-f6893270c4ee)
![blablahrandomnameforphoto](https://github.com/user-attachments/assets/4de70287-3d1f-44c8-9226-7a807aa5c28b)

My mind didn't think of checking the settings, now the recipees appearing before it is even researched is fixed.

In the photos I am showing the duplicate recipees I found

**Comment by LuziferSenpai** [comment]
That is not duplicate recipes.
That is casting & crafting.
One is using no fluids, the other is using fluids.
