### ISSUE TITLE
[BUG] more-casting / molten-tungsten: hard craash on start up

### ISSUE THREAD

**Issue by Krasna45** [LuziferSenpai/factorio-mods#4]
**Describe the bug**
Factorio throws an error when loading mods and having more-casting or molten-tungsten on

**To Reproduce**
1. Check more-casting or molten-tungsten in mods
2. Restart game
3 See error

**Expected behavior**
Start up game

**Mod Information**
- Mod Name: more-casting (0.0.5), molten-tungsten (0.0.3)

**Factorio Error Report**
stack traceback:
	__more-casting__/data-final-fixes.lua:203: in function 'fct'
	__core__/lualib/meld.lua:25: in function '?'
	__core__/lualib/meld.lua:46: in function <__core__/lualib/meld.lua:41>
	(...tail calls...)
	__more-casting__/data-final-fixes.lua:201: in main chunk

stack traceback:
	__molten-tungsten__/data-final-fixes.lua:175: in function 'fct'
	__core__/lualib/meld.lua:25: in function '?'
	__core__/lualib/meld.lua:46: in function <__core__/lualib/meld.lua:41>
	(...tail calls...)
	__molten-tungsten__/data-final-fixes.lua:173: in main chunk

**Comment by LuziferSenpai** [comment]
What other mods do you have installed?

**Comment by Krasna45** [comment]
Here's the modlist
[mod-list.json](https://github.com/user-attachments/files/17522274/mod-list.json)

**Comment by LuziferSenpai** [comment]
This is a problem with [Fluid Permutations Fixed](https://mods.factorio.com/mod/fluid_permutations_fixed). I dont even know why this mod still exists. In the base game you can flip the order of fluid inputs with the hotkeys for `Flip horizontal` & `Flip vertical`.
