### ISSUE TITLE
[BUG] Newest version of Electronic Trains crashes after few seconds

### ISSUE THREAD

**Issue by FluffyDiscord** [LuziferSenpai/factorio-mods#6]
**Describe the bug**
After loading a map with existing electric train network, it takes only few seconds until game crashes. Only happens in the newest version

**Screenshots**
![image](https://github.com/user-attachments/assets/7ed4e496-8da8-4309-bec6-623e9f6abb49)

**Comment by xeonight** [comment]
Seconded, game crashes after about 30 seconds after loading.

**Comment by LuziferSenpai** [comment]
I'm working on, something really shitty happend.

**Comment by FluffyDiscord** [comment]
> I'm working on, something really shitty happend.

No, you just have a typo on thst line that can be seen in my screenshot

**Comment by LuziferSenpai** [comment]
Nop, I didnt change that. That happend because of LuaLS. But there is another problem I saw just now, with my changes.

**Comment by xeonight** [comment]
Thank you for your work on the mod! i know its out of your free time, so it's Much appreciated!

**Comment by LuziferSenpai** [comment]
Is fixed with the newest release

**Comment by LuziferSenpai** [comment]
Fixed with https://github.com/LuziferSenpai/factorio-mods/commit/3fefbcc0d15e2de89643d52b452509205c7e7ed9
