### ISSUE TITLE
[FEATURE]Captain's log line limit

### ISSUE THREAD

**Issue by mpwoz** [LuziferSenpai/factorio-mods#7]
Is there a limit to the number of entries in Captain's log? Some of them are getting quite long and I need to scroll all the way to the bottom to see them - another option would be to sort them in descending chronological order (recent first)

Otherwise great mod and really helpful for debugging shipping issues without having to watch a ship sail for hours!

**Comment by LuziferSenpai** [comment]
Yea, a reverse order button would be good.
Will work on it.

**Comment by LuziferSenpai** [comment]
Will come with the next release
![Screenshot 2024-11-07 074259](https://github.com/user-attachments/assets/eb46f14a-1158-43f8-b986-b02b1afa4d85)

**Comment by LuziferSenpai** [comment]
Added with https://github.com/LuziferSenpai/factorio-mods/commit/90696fc55ca4aaf54baf6117d5b44897d65c4d7f
