### ISSUE TITLE
Mark Metallurgy Recipes as hide_from_player_crafting = true so they do not show on Player crafting menu

### ISSUE THREAD

**Issue by SkeletonGear** [LuziferSenpai/factorio-mods#8]
At present Recipes cause mass clutter in the player crafting menu due to duplicating recipes.
Marking hide_from_player_crafting = true on the recipe as below after line 190 will make the recipes only show on selecting the foundry as recipes on machines are not hidden. this will declutter the metalurgy recipes from the player crafting list

if moltenIronAmount > 0 or moltenCopperAmount > 0 then
                data:extend({
                    meld(table.deepcopy(recipe), {
                        name = "casting-" .. item.name,
                        icons = makeCastingIcons(item, { moltenIronAmount = moltenIronAmount, moltenCopperAmount = moltenCopperAmount }),
                        localised_name = { "more-casting.casting", { "?", { "entity-name." .. item.name }, { "item-name." .. item.name }, { "equipment-name." .. item.name } } },
                        category = "metallurgy",
                        subgroup = "casting-" .. item.subgroup,
                        ingredients = meld.overwrite(ingredients),
                        allow_decomposition = false,
                        enabled = false,
			hide_from_player_crafting = true
                    })
                })

**Comment by LuziferSenpai** [comment]
I actually had this on purpose, because the standard casting recipes are that way too.

**Comment by LuziferSenpai** [comment]
Done with https://github.com/LuziferSenpai/factorio-mods/commit/7eeccd70d247993f40685766738b2bd607573db2
