### ISSUE TITLE
[FEATURE] Compatibility with Foundry Expanded (if necessary)?

### ISSUE THREAD

**Issue by BlastYoBoots** [LuziferSenpai/factorio-mods#9]
**DISCLAIMER: I haven't had time yet to these mods for existing compatibility, so this may be a non-issue.**  Would you consider checking if compatibility is possible or even necessary to implement for [Foundry Expanded](https://mods.factorio.com/mod/foundry-expanded)?  For those who prefer the more limited but productivity-enabled selection they have to offer to the More Casting mod you implemented.  No obligation to do so unless you feel it's worthwhile of course.  I found another to look into, [Foundry Restructuring](https://mods.factorio.com/mod/foundry-restructuring), but the first is my selfish preference.

PS, If the Mod Page descriptions of More Casting and Molten Tungsten listed the items which were newly castable (and the new casting recipes) it would be easier to compare the mods to similar offerings.

**Comment by LuziferSenpai** [comment]
Sry, but with the automation I have for the recipes I will not make any changes or have a lookup table for other mods that add recipes without automation.
So the other mod author should make the changes or do something.

**Comment by BlastYoBoots** [comment]
Perfectly understandable, thank you!
